#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euo pipefail

cd "$(dirname $0)"/..

# 2) Install system deps
sudo apt update && sudo apt upgrade -y && xargs -a apt-packages.txt sudo apt install -y
xargs -a snap-packages.txt sudo snap install -y
[ -f /var/run/reboot-required ] && sudo reboot -f


# 4) Oh-My-Zsh & plugins
# ~/.dotfiles/install-omz.sh

DOTFILES="$HOME/.dotfiles"
if [ ! -d "$DOTFILES" ]; then
  git clone https://github.com/scurry/my-dotfiles.git "$DOTFILES"
fi
cd "$DOTFILES"

# ensure dotbot is present
if [ ! -x bin/dotbot/bin/dotbot ]; then
  git submodule update --init --recursive
fi

# run the manifest
bin/dotbot/bin/dotbot -c install.conf.yaml
echo "✅ Dotfiles applied!"

# find the installers and run them iteratively
# find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

