name: CI ― Validate & Bootstrap

on:
  push:
    paths:
      - 'dotfiles/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 3 * * 1'   # weekly on Mondays at 03:00 UTC
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install prerequisites
        run: sudo apt update && sudo apt install -y git zsh python3

      - name: Run bootstrap script
        run: bash dotfiles/install.sh

      - name: Smoke-test Zsh startup
        run: zsh --login -c exit

  update-plugins:
    runs-on: ubuntu-latest
    needs: test-install
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update Zsh plugins submodules
        run: |
          cd dotfiles
          git submodule foreach 'git fetch && git checkout origin/master'
          git add .
          git commit -m "ci: bump Zsh plugin submodules" || echo "No changes"
          git push
